### ISSUE TITLE
Getting the attribute LunchBooking and DinnerBooking always return None

### ISSUE THREAD

**Issue by SpiralNuggets** [chananon-n/FineCuisine#44]
Upon the confirmation of the reservation, the system does not see the immediate booking, and saying "Booking not available"
![image](https://github.com/chananon-n/FineCuisine/assets/68524576/7105e11c-6d0e-465c-b127-275be1cffda4)
![image](https://github.com/chananon-n/FineCuisine/assets/68524576/b9a47784-fb32-49aa-9037-8a776057794d)

Upon further inspection, the issue arises from the fact that `checkAvailable` in `reservation()` always return `False`. `checkBookingAvailable()` returns this.
![image](https://github.com/chananon-n/FineCuisine/assets/68524576/d1162127-dcd0-4c54-b6e5-637713daf889)

Further backtracking reveals that `bookInfo` is `None`, this giving the output of `false`. This means that `getMealBooking` returns `None`.
![image](https://github.com/chananon-n/FineCuisine/assets/68524576/c8f0fd85-311a-454c-b42b-a711152a1700)

Which is the result of `getattr(root, f'{meal_type}Booking').values()` not finding anything. Which skips the condition check as the iterator has nothing to work with.
![image](https://github.com/chananon-n/FineCuisine/assets/68524576/1a0eb36d-1f6c-4343-ac0e-a51b0f331268)

To sums it all up:

1. `checkAvailable` relies on `checkBookingAvailable` which returns `False`.
2. `checkBookingAvailable` returns False because `bookInfo` is `None`.
3. `getMealBooking` returns None which leads to `bookInfo` being `None`.
4. This happens because `getattr(root, f'{meal_type}Booking').values()` doesn't find anything.

I could fork this and make a pull request but I do not have a complete knowledge of your system's layout and requirements. I hope whoever writing this part takes responsibility.

**Comment by annopdanai** [comment]
#50 should fixed this
